apiVersion: v1
kind: Namespace
metadata:
  name: acd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acd-deploy
  namespace: acd
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: acd
  template:
    metadata:
      labels:
        app: acd
    spec:
      containers:
      - name: acd
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acd-svc
  namespace: acd
  labels:
    app: acd
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: acd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acd-ingress
  namespace: acd
spec:
  rules:
  - host: "acd.wescodevops.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: acd-svc 
            port:
              number: 80
  tls:
  - hosts:
    - aacd.wescodevops.home
    secretName: acd-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acd-cert
  namespace: acd
spec:
  secretName: acd-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - acd.wescodevops.home
